spring.application.name=user
spring.mongodb.uri=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@user-data.nvuisah.mongodb.net/?appName=user-data
spring.mongodb.database=user_db
server.port=8082

logging.level.org.springframework.data.mongodb=DEBUG